=======================================================
CRIAR USUÁRIO
=======================================================
###
POST http://localhost:3000/usuarios

Content-Type: application/json

{
"nome": "dias",
"telefone": "54666232730",
"email": "dias@example.com",
"endereco": "santa maria"
}

=======================================================
LISTAR TODOS OS USUÁRIOS
=======================================================
###
GET http://localhost:3000/usuarios

=======================================================
BUSCAR USUÁRIO POR ID
=======================================================
###
GET http://localhost:3000/usuarios/1

=======================================================
ATUALIZAR UM USUÁRIO POR ID
=======================================================
###
PUT http://localhost:3000/usuarios/1

Content-Type: application/json

{
"nome": "Yasmim Dias",
"email": "dias@example.com
"
}

=======================================================
DELETAR USUÁRIO POR ID
=======================================================
###
DELETE http://localhost:3000/usuarios/1

=======================================================
CRIAR CARTÃO PARA UM USUÁRIO
=======================================================
###
POST http://localhost:3000/cartoes

Content-Type: application/json

{
"usuario_id": 2,
"numero": "5555 4444 3333 2222",
"cvv": "789",
"validade": "09/29"
}

=======================================================
LISTAR TODOS OS CARTÕES
=======================================================
###
GET http://localhost:3000/cartoes

=======================================================
LISTAR USUÁRIOS COM SEUS CARTÕES (JOIN)
=======================================================
###
GET http://localhost:3000/usuarios-com-cartoes